language: python
python:
  - 2.6
  - 2.7

install:
  - pip install -r pip-requires --use-mirrors
  # unittest2 is only required for testing on 2.6
  - pip install unittest2

before_script:
  - psql -c "CREATE DATABASE popcorn;" -U postgres
  - psql -c "CREATE USER popcorn WITH PASSWORD 'popcorn';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE popcorn TO popcorn;" -U postgres

script:
  - python setup.py test